sudo: required
dist: trusty
services:
  - docker
language: rust

matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
           NO_ADD=1
      if: branch != master
      osx_image: xcode9
    - os: osx
      env: TARGET=x86_64-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
           NO_ADD=1
      if: branch != master
      osx_image: xcode9.1
    - os: osx
      env: TARGET=x86_64-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
           NO_ADD=1
      if: branch != master
      osx_image: xcode9.2
    - os: osx
      env: TARGET=x86_64-apple-darwin
           MACOSX_DEPLOYMENT_TARGET=10.7
           NO_ADD=1
      if: branch != master
      osx_image: xcode9.3
  allow_failures:
    - env: TARGET=x86_64-unknown-netbsd
           DOCKER=alexcrichton/rust-slave-linux-cross:2016-11-11
           SKIP_TESTS=1

cache:
  # We're going to download things we don't necessarily want to cache into the `target` directory, so
  # don't use travis's native `cargo` caching, which just grabs the whole folder.
  directories:
    - target/$TARGET/openssl/openssl-install
    - target/release/deps

install:
  - if [ -z "$NO_ADD" ]; then rustup target add $TARGET; fi

script:
  - mkdir -p target/$TARGET;
  - >
      if [ ! -z "$DOCKER" ]; then
          sh ci/build-run-docker.sh "$DOCKER" "$TARGET" "$SKIP_TESTS";
      else
          PATH=$HOME/rust/bin:$PATH sh ci/run.sh;
      fi

before_deploy:
  - bash ci/prepare-deploy-travis.sh

deploy:
  - provider: s3
    bucket: dev-static-rust-lang-org
    skip_cleanup: true
    local_dir: deploy
    upload_dir: rustup
    acl: public_read
    region: us-west-1
    access_key_id: AKIAJFCDPYKTBQVIFTDQ
    secret_access_key:
      secure: "fcKM0bWHz1UJVnZdQl/kCrFCykDkdwOAy1o5LAsUEkgNwSiWF4qC2sqHUbz2hCIe2tD5D8UCqa7brgSz0HNTL1yvSeOO/0Vim8xP9ev9SMf0Muekq0Wj/Kw4kJ3C4ajHdOdF2zXGnw9tsitzylLqx/r8cu0S8UtI49sIAWF3+/dD/uGnXu+wtaYiUJ1znirDzq74rHLrk8M/kQDFTrDJ8D+wXbKSJP9nmKkFShkW8A71QmaCOUqG3q7SpylY81rKRjHjtXCWJ3CHkD7XpdxdsImnukDtt8OndJH+9691TPKcR/RUC/dnUYg5QignmV83AN84c2/6ZykarQ9M/ziBYRI92bj0vPhoHu/vk2HY1VgWlX9qbXfVzd8glfmtS6be7eNYPtEHxoSu9o6WSbVaFv/07IapY/f7vE0kflvW58hRjdy8k4Sv31qPFO0hs7NFJMCRCam/uPpWKTEhfIjAJH6PoXOvND92ZHi9rjnwfVtXEClYtl5vPkRgPTkKJXzF+jVl9sDX1WhZhfgqRNNWEVyfoiptNxHygavDGCPsjpKVMmvntM8dsMZmewSeKemratN2seTP5q4d/IVbgONXiH/SDFhzXkIy4W/MdbxEjXBaVW0DT7x5k/CZhx1ZBIquWhE52nZWpBsJdpCiWl9AORDYVQnCjNp8hWXX7TlIBe4="
    on:
      branch: stable
